[package]
name = "tui-template"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
eyre = "0.6.5"
seahorse = "1.1.2"
tokio = { version = "1", features = ["full"] }
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
